### PR TITLE
Change gldas test data

### PR DESCRIPTION
**Pull request by wpreimes**
@sebhahn: I added a new function to the gldas package (ts generation from land points only) and want to use netcdf files for testing instead of grib files (the land mask used is fit to newer versions of gldas which are netcdf). Do you know if changing this, affects packages other than the gldas package (are other packages using this submodule)?

### CODE REVIEW

**Comment by sebhahn** [comment]
Changing the submodule won't effect other packages using this one as a subpackage immediately, because other packages would need to update to a new version of this one and only then can have troubles with e.g. missing data.

**Comment by sebhahn** [comment]
Maybe we can keep the grb files as well, can't we?

**Comment by wpreimes** [comment]
ok, I will keep grb and add the netcdf files separately

**Comment by wpreimes** [comment]
Ok now the old files are kept

**Pull request merged**
